from __future__ import annotations

from typing import Any


FIELD_DEFINITIONS: dict[str, dict[str, Any]] = {
    "energy_efficiency_label": {
        "field_key": "energy_efficiency_label",
        "display_name_zh": "能效标签",
        "aliases": (
            "ENERGY EFFICIENCY LABEL",
            "ENERGY LABEL",
            "能效标签",
            "ÉTIQUETTE ÉNERGÉTIQUE",
            "بطاقة كفاءة الطاقة",
        ),
        "expected_value_type": "presence",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("presence",),
        "min_confidence_for_pass": 0.75,
    },
    "washing_machine": {
        "field_key": "washing_machine",
        "display_name_zh": "洗衣机",
        "aliases": ("WASHING MACHINE", "洗衣机", "MACHINE À LAVER", "غسالة ملابس"),
        "expected_value_type": "presence",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("presence",),
        "min_confidence_for_pass": 0.75,
    },
    "energy_class": {
        "field_key": "energy_class",
        "display_name_zh": "能效等级",
        "aliases": ("ENERGY CLASS", "ENERGY EFFICIENCY CLASS", "能效等级", "CLASSE ÉNERGÉTIQUE", "فئة كفاءة الطاقة"),
        "expected_value_type": "class",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "annual_energy_consumption": {
        "field_key": "annual_energy_consumption",
        "display_name_zh": "年耗电量",
        "aliases": (
            "ANNUAL ENERGY CONSUMPTION",
            "ENERGY CONSUMPTION",
            "年耗电量",
            "耗电量",
            "CONSOMMATION ANNUELLE D'ÉNERGIE",
            "CONSOMMATION D'ÉNERGIE",
            "استهلاك الطاقة السنوي",
        ),
        "expected_value_type": "number",
        "expected_units": ("kWh",),
        "forbidden_values": ("Liter", "Litre", "kg"),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "annual_water_consumption": {
        "field_key": "annual_water_consumption",
        "display_name_zh": "年耗水量",
        "aliases": (
            "ANNUAL WATER CONSUMPTION",
            "WATER CONSUMPTION",
            "年耗水量",
            "用水量",
            "CONSOMMATION ANNUELLE D'EAU",
            "CONSOMMATION D'EAU",
            "استهلاك المياه السنوي",
        ),
        "expected_value_type": "number",
        "expected_units": ("Liter", "Litre", "L"),
        "forbidden_values": ("kWh", "kg"),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "capacity": {
        "field_key": "capacity",
        "display_name_zh": "容量",
        "aliases": ("CAPACITY", "容量", "CAPACITÉ", "السعة"),
        "expected_value_type": "number",
        "expected_units": ("kg", "L"),
        "forbidden_values": ("kWh", "Liter", "Litre"),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "water_consumption_efficiency": {
        "field_key": "water_consumption_efficiency",
        "display_name_zh": "水耗效率",
        "aliases": ("WATER CONSUMPTION EFFICIENCY", "水耗效率", "كفاءة استهلاك المياه"),
        "expected_value_type": "class",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.70,
    },
    "water_extraction_efficiency": {
        "field_key": "water_extraction_efficiency",
        "display_name_zh": "脱水效率",
        "aliases": ("WATER EXTRACTION EFFICIENCY", "脱水效率", "كفاءة استخراج المياه"),
        "expected_value_type": "class",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.70,
    },
    "type": {
        "field_key": "type",
        "display_name_zh": "类型",
        "aliases": ("TYPE", "类型", "TYPE D'APPAREIL", "النوع"),
        "expected_value_type": "enum",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern"),
        "enum_values": ("TOP LOAD", "FRONT LOAD", "TWIN TUB", "WITH DRYER"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "made_in": {
        "field_key": "made_in",
        "display_name_zh": "产地",
        "aliases": ("MADE IN", "COUNTRY OF ORIGIN", "产地", "制造地", "FABRIQUÉ EN", "PAYS D'ORIGINE", "بلد الصنع"),
        "expected_value_type": "country",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern", "brand_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "brand_name": {
        "field_key": "brand_name",
        "display_name_zh": "品牌名称",
        "aliases": ("BRAND NAME", "BRAND", "品牌", "品牌名称", "MARQUE", "NOM DE MARQUE", "العلامة التجارية"),
        "expected_value_type": "brand",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern", "country_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "model_number": {
        "field_key": "model_number",
        "display_name_zh": "型号",
        "aliases": ("MODEL NUMBER", "MODEL NO", "MODEL", "产品型号", "规格型号", "型号", "MODÈLE", "NUMÉRO DE MODÈLE", "رقم الطراز"),
        "expected_value_type": "model_code",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": ("standard_number_pattern", "country_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "standard_reference_no": {
        "field_key": "standard_reference_no",
        "display_name_zh": "标准编号",
        "aliases": (
            "STANDARD REFERENCE NO",
            "STANDARD REFERENCE NUMBER",
            "STANDARD NO",
            "REFERENCE NO",
            "标准编号",
            "依据国家标准",
            "依据标准",
            "RÉFÉRENCE DE LA NORME",
            "NUMÉRO DE NORME",
            "الرقم المرجعي للمواصفة",
        ),
        "expected_value_type": "standard_code",
        "expected_units": (),
        "forbidden_values": ("REFERENCE NO", "STANDARD REFERENCE NO"),
        "forbidden_patterns": ("model_number_pattern", "country_pattern", "company_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "registration_no": {
        "field_key": "registration_no",
        "display_name_zh": "注册号",
        "aliases": ("REGISTRATION NO", "REGISTRATION NUMBER", "注册号", "NUMÉRO D'ENREGISTREMENT", "رقم التسجيل"),
        "expected_value_type": "registration_code",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": ("company_pattern", "country_pattern", "field_name_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "manufacturer_name": {
        "field_key": "manufacturer_name",
        "display_name_zh": "生产者名称",
        "aliases": ("生产者名称", "生产者", "制造商", "制造商名称", "生产企业", "MANUFACTURER", "MANUFACTURER NAME", "PRODUCER", "PRODUCER NAME", "COMPANY NAME"),
        "expected_value_type": "manufacturer",
        "expected_units": (),
        "forbidden_values": ("China", "中国"),
        "forbidden_patterns": ("country_pattern", "model_number_pattern", "standard_number_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "cleaning_ratio": {
        "field_key": "cleaning_ratio",
        "display_name_zh": "洗净比",
        "aliases": ("洗净比", "洗涤比", "WASH RATIO", "CLEANING RATIO"),
        "expected_value_type": "number",
        "expected_units": (),
        "forbidden_values": ("kg", "kWh", "Liter"),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "wash_spin_capacity": {
        "field_key": "wash_spin_capacity",
        "display_name_zh": "洗涤/脱水容量",
        "aliases": ("洗涤/脱水容量", "洗涤脱水容量", "洗涤容量/脱水容量", "WASH/SPIN CAPACITY", "WASHING/SPINNING CAPACITY"),
        "expected_value_type": "capacity_pair",
        "expected_units": ("kg",),
        "forbidden_values": ("kWh", "Liter"),
        "forbidden_patterns": ("model_number_pattern", "standard_number_pattern"),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "drawing_code": {
        "field_key": "drawing_code",
        "display_name_zh": "图纸编号",
        "aliases": ("图纸编号", "图纸编码", "DRAWING CODE", "DRAWING NO", "DWG NO", "DWG"),
        "expected_value_type": "code",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "label_code": {
        "field_key": "label_code",
        "display_name_zh": "编码",
        "aliases": ("编码", "标签编码", "LABEL CODE", "CODE", "PART NO"),
        "expected_value_type": "code",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
    "label_name": {
        "field_key": "label_name",
        "display_name_zh": "标签名称",
        "aliases": ("标签名称", "LABEL NAME", "LABEL", "铭牌"),
        "expected_value_type": "text",
        "expected_units": (),
        "forbidden_values": (),
        "forbidden_patterns": (),
        "preferred_spatial_relation": ("same_row", "near_left", "near_right"),
        "min_confidence_for_pass": 0.75,
    },
}


def get_field_definition(field_key: str) -> dict[str, Any] | None:
    definition = FIELD_DEFINITIONS.get(field_key)
    return dict(definition) if definition else None


def all_field_definitions() -> list[dict[str, Any]]:
    return [dict(item) for item in FIELD_DEFINITIONS.values()]


def aliases_for_field(field_key: str) -> tuple[str, ...]:
    definition = FIELD_DEFINITIONS.get(field_key, {})
    return tuple(definition.get("aliases", ()))


def display_name_for_field(field_key: str) -> str:
    return str(FIELD_DEFINITIONS.get(field_key, {}).get("display_name_zh", field_key))
